### PR TITLE
Added horizontal picker support

### PR DESCRIPTION
**Pull request by pedromassango**
I just added the horizontal picker support, it is working as expected.

### CODE REVIEW

**Comment by delef** [comment]
Merge this?

**Comment by pedromassango** [comment]
Is there anything that I should do to merge this?

**Comment by aravind816** [comment]
When this bug fix will be released for use. I need this feature.

**Comment by aravind816** [comment]
When this bug fix will be released for use. I need this feature.

**Comment by Drkstr** [comment]
Any updates on this? I would like to use it in a project.

**Pull request merged**
