### PR TITLE
Added a text mapper to customize number text

### PR DESCRIPTION
**Pull request by HugoSart**
This code introduces the TextMapper, that is a function defined by the user of this widget to map the text displayed by the widget. This way, the user can define it's own code to show a custom text instead of just a plain number.

### CODE REVIEW

**Comment by HugoSart** [comment]
How do I fix the coverage problem?

**Comment by MarcinusX** [comment]
Hi!

Shouldn't the mapper map int value to string?

> How do I fix the coverage problem?
Add tests :)

**Comment by HugoSart** [comment]
> Hi!
> 
> Shouldn't the mapper map int value to string?
> 
> > How do I fix the coverage problem?
> 
> Add tests :)

I let it as string to not mess with the number padding.

**Comment by HugoSart** [comment]
@MarcinusX Can you give some hints about how to write the proper tests to pass the coverage analysis?

**Comment by zerox1212** [comment]
Will you merge this? A single integer number picker is too limited, we need to be able to put strings into the picker.

**Comment by samsheldin** [comment]
please merge this this  is a required feature

**Comment by AlecSPb** [comment]
Is there a solution to this request?

**Comment by samsheldin** [comment]
Not sure. I have  to try out something , then I'll inform you

**Comment by AlecSPb** [comment]
That's what I did. All values change simultaneously, it should not be so. 
anim

**Comment by MarcinusX** [comment]
Hey. I will merge and publish it in a few days. I'm super busy and can't put much time into this package, so all the code, tests and screenshots are very welcome!.

**Comment by samsheldin** [comment]
Thanks guys, god bless you

**Comment by MarcinusX** [comment]
Published as 1.2.0!
Thank you very much for your contribution!

**Comment by Hatesh8** [comment]
Can anyone please tell me how can i use textMapper?

**Comment by Hatesh8** [comment]
> That's what I did. All values change simultaneously, it should not be so.
> anim

Did you achieve this?

**Pull request merged**
