### PR TITLE
Deprecated ThemeData.accentColor with ThemeData.colorScheme.secondary

### PR DESCRIPTION
**Pull request by litang0908**

### CODE REVIEW

**Comment by ndelanou** [comment]
I got build errors with the new Flutter beta build (3.9.0-0.1.pre)
This PR fixes it

**Comment by prologikus** [comment]
@ndelanou same here, please accept this @jmolins @insin @hamaluik @

**Comment by giovanni256** [comment]
Same here

**Comment by etiennedv-mathu** [comment]
pls merge

**Comment by hamaluik** [comment]
Thanks!

**Comment by SiriusArtLtd** [comment]
Pls merge!

**Comment by MarcinusX** [comment]
Closing in favor of https://github.com/MarcinusX/NumberPicker/commit/566ab314da385d76df0405c990bd4d5ad6562dcc
The issue should be fixed in version 2.1.2

**Pull request closed without merging**
